# Generated by Django 3.1.2 on 2020-12-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_count',
            field=models.IntegerField(null=True),
        ),
    ]
