# Generated by Django 3.1.2 on 2020-12-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20201230_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_attempt',
            field=models.IntegerField(null=True),
        ),
    ]
